### ISSUE TITLE
Question: did you implement transform xml result to archive?

### ISSUE THREAD

**Issue by kdelee** [ibutsu/ibutsu-client-python#4]
@unlikelyzero and I were looking and we can't find an option to take an existing xml result file and produce an uploadable/importable archive.

I remember us talking about feature being on the roadmap -- are we just not finding it, or is it not done yet?

**Comment by kdelee** [comment]
@rsnyman ^

**Comment by rsnyman** [comment]
If the file is already in xUnit format, you can just upload it using the import API endpoint.

**Comment by kdelee** [comment]
Thanks!
